---
- name: Delete a guest VM through vCenter.
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    vcenter_hostname: ****
    vcenter_user: ****
    vcenter_pass: ****
    datacenter: PCSp
    cluster: vSAN
    folder: 1002350
    esxi_hostname: pcsp-proto02.ad.proto.skp
    vm_templete: skp_centos7

    #guest_hostname: svc-host-03
    #guest_name: "svc-host-03 (unknown)"
    #guest_ip: 175.126.56.223
    guest_netmask: 255.255.255.0
    guest_gateway: 175.126.56.1

  tasks:
  - name: Guest VM shutdown
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      validate_certs: no
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      guest: "{{ guest_name }}"
      #state: powered_off
      state: absent
      force: yes