---
- name: Create a guest VM with nova
  hosts: osc
  gather_facts: false
  connection: local
  
  vars:
    #function: create_server
    function: get_network_list
  
  tasks:
  - name: Gather facts about previously created networks
    os_networks_facts:
      auth:
        auth_url: http://api.ocs.skplanet.com:5000/v3
        username: 1002350
        password: moomoo507! 
        project_name: default
        #project_id: dbf3d08c56e1472fb6462b9a0a1b087b
    when: function == "get_network_list"

  - name: Show openstack networks
    debug:
      var: openstack_networks
    when: function == "get_network_list"
      
  - name: create server
    nova_compute:
      state: present
      login_username: 1002350
      login_password: moomoo507!
      login_tenant_name: skp
      name: moo-moo-moo
      auth_url: http://api.ocs.skplanet.com:5000/v3
      region_name: API_TEST
      availability_zone: 
      image_id: 45124e45-eea9-4fbe-b91f-6a34d0220d9a
      wait_for: 200
      flavor_id: 02a7e84e-e032-49a7-bd46-e3f7e0e99986
      security_groups: default
      nics:
        - net-id: 34605f38-e52a-25d2-b6ec-754a13ffb723
      meta:
        hostname: test1
        group: uge_master
      when: function == "create server"



